Repository microsoft/kata-containers, pull requests merged in 2024-04, with the labels that each got.

#172 genpolicy sync upstream [2/3]
  src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
  src/tools/genpolicy/genpolicy-settings.json
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/obj_meta.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/settings.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/yaml.rs
Labels: upstream/not-needed

#169 Add support to handle SMB mounts
  src/agent/src/device.rs
  src/agent/src/storage/fs_handler.rs
  src/agent/src/storage/mod.rs
  src/runtime/pkg/direct-volume/utils.go
  src/runtime/virtcontainers/container.go
  src/runtime/virtcontainers/kata_agent.go
Labels: upstream/missing

#163 genpolicy: use containerd_client
  .github/workflows/static-checks.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/rc-nginxhttps.yaml
  src/agent/samples/policy/yaml/kubernetes/unsupported-image/mysql-galera-statefulset.yaml
  src/agent/samples/policy/yaml/kubernetes/unsupported-image/nginxrc.yaml
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
  src/tools/genpolicy/policy_samples.json
  src/tools/genpolicy/src/config_map.rs
  src/tools/genpolicy/src/daemon_set.rs
  src/tools/genpolicy/src/deployment.rs
  src/tools/genpolicy/src/job.rs
  src/tools/genpolicy/src/list.rs
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/no_policy.rs
  src/tools/genpolicy/src/pod.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
  src/tools/genpolicy/src/replica_set.rs
  src/tools/genpolicy/src/replication_controller.rs
  src/tools/genpolicy/src/secret.rs
  src/tools/genpolicy/src/stateful_set.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/yaml.rs
  src/tools/genpolicy/update_policy_samples.py
Labels: upstream/merged

#175 genpolicy: support read-only hostPath
  src/agent/samples/policy/yaml/kubernetes/conformance/conformance-e2e.yaml
  src/tools/genpolicy/src/mount_and_storage.rs
Labels: upstream/missing

#176 genpolicy: add --version flag
  src/tools/genpolicy/.gitignore
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/Makefile
  src/tools/genpolicy/src/main.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/src/version.rs.in
Labels: upstream/missing

#179 agent: shutdown vm on exit when agent is used as init process
  src/agent/src/main.rs
Labels: upstream/merged

#181 genpolicy: add missing cache improvements
  src/tools/genpolicy/src/registry.rs
  src/tools/genpolicy/src/registry_containerd.rs
Labels: upstream/merged

#185 genpolicy: bump release version
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
Labels: upstream/not-needed

#184 agent: use regorus instead of opa
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/samples/policy/yaml/pod/pod-spark.yaml
  src/agent/src/main.rs
  src/agent/src/policy.rs
Labels: upstream/merged
