Repository microsoft/kata-containers, pull requests merged in 2024-07, with the labels that each got.

#208 samples: introduce incomplete_init category
  src/tools/genpolicy/policy_samples.json
  src/tools/genpolicy/update_policy_samples.py
Labels: upstream/not-needed

#206 Cherry-pick upstream PR #9825: osbuilder: allow rootfs builds w/o git or version file deps
  src/agent/Makefile
  src/runtime-rs/Makefile
  src/tools/kata-ctl/Makefile
  src/tools/log-parser/Makefile
  tools/osbuilder/Makefile
  tools/osbuilder/rootfs-builder/rootfs.sh
  tools/osbuilder/scripts/lib.sh
Labels: upstream/merged

#204 tools: Improve igvm-builder and node-builder/azure-linux scripting
  src/runtime/Makefile
  src/runtime/arch/amd64-options.mk
  src/runtime/arch/arm64-options.mk
  src/runtime/config/configuration-clh-snp.toml.in
  tools/osbuilder/.gitignore
  tools/osbuilder/Makefile
  tools/osbuilder/igvm-builder/azure-linux/config.sh
  tools/osbuilder/igvm-builder/azure-linux/igvm_lib.sh
  tools/osbuilder/igvm-builder/igvm_builder.sh
  tools/osbuilder/node-builder/azure-linux/Makefile
  tools/osbuilder/node-builder/azure-linux/README.md
  tools/osbuilder/node-builder/azure-linux/clean.sh
  tools/osbuilder/node-builder/azure-linux/common.sh
  tools/osbuilder/node-builder/azure-linux/package_build.sh
  tools/osbuilder/node-builder/azure-linux/package_install.sh
  tools/osbuilder/node-builder/azure-linux/uvm_build.sh
  tools/osbuilder/node-builder/azure-linux/uvm_install.sh
Labels: upstream/missing

#209 tardev: update tardev-snapshotter.service
  src/tardev-snapshotter/tardev-snapshotter.service
Labels: upstream/missing

#210 samples: reduce dependencies to docker hub
  src/agent/samples/policy/yaml/kubernetes/conformance/csi-hostpath-testing.yaml
  src/agent/samples/policy/yaml/kubernetes/incomplete-init/cockroachdb-statefulset.yaml
  src/agent/samples/policy/yaml/pod/pod-ubuntu.yaml
  src/tools/genpolicy/policy_samples.json
Labels: upstream/not-needed
