Repository microsoft/kata-containers, pull requests merged in 2024-12, with the labels that each got.

#254 node-builder: Deploy-only recipe for AzL3 VMs
  tools/osbuilder/node-builder/azure-linux/README.md
  tools/osbuilder/node-builder/azure-linux/common.sh
  tools/osbuilder/node-builder/azure-linux/package_tools_install.sh
  tools/osbuilder/node-builder/azure-linux/uvm_install.sh
Labels: upstream/not-needed

#253 runtime: skip logging some of the dial errors
  src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
Labels: upstream/missing, upstream/merged

#260 policy: ignore optional metadata uid field
  src/agent/samples/policy/yaml/pod/pod-one-container.yaml
  src/tools/genpolicy/src/obj_meta.rs
Labels: upstream/merged

#264 samples: replicate nginx image to private ACR
  src/agent/samples/policy/yaml/deployment/deployment-front.yaml
  src/agent/samples/policy/yaml/dont-enable-kata-debug/pod-lots-of-layers.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/appsv1deployment.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/deploy-clientside.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/rc-lastapplied.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/rc-noexist.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures/replication.yaml
  src/agent/samples/policy/yaml/kubernetes/fixtures2/rc-service.yaml
  src/agent/samples/policy/yaml/pod/pod-many-layers.yaml
  src/agent/samples/policy/yaml/stateful-set/web.yaml
  src/agent/samples/policy/yaml/stateful-set/web2.yaml
Labels: upstream/not-needed

#265 runtime: Set memory config shared=false when shared_fs=None in CLH
  src/runtime/virtcontainers/clh.go
Labels: upstream/merged

#266 agent: fix make test
  src/agent/src/device.rs
Labels: upstream/not-needed

#269 chore: bump release version
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
Labels: upstream/not-needed

#270 node-builder: Minor updates to README.md
  tools/osbuilder/node-builder/azure-linux/README.md
Labels: upstream/not-needed

#274 chore: bump release version
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
Labels: upstream/not-needed

#279 chore: bump genpolicy bump genpolicy version
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
Labels: upstream/not-needed
