Repository microsoft/kata-containers, pull requests merged in 2024-02, with the labels that each got.

#158 genpolicy: update policy sample
  src/agent/samples/policy/yaml/pod/pod-ubuntu.yaml
Labels: upstream-not-needed

#160 tarfs reliability fixes
  src/tarfs/tarfs.c
Labels: upstream/not-needed

#154 Adapt code for vanilla Kata
  src/runtime/Makefile
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/resourcecontrol/cgroups.go
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: upstream/missing

#164 Saulparedes/fix ingress test
  src/agent/samples/policy/yaml/kubernetes/conformance2/ingress-nginx-rc.yaml
  src/agent/samples/policy/yaml/pod/pod-ubuntu.yaml
  src/tools/genpolicy/src/yaml.rs
Labels: upstream/not-needed
