Repository microsoft/kata-containers, pull requests merged in 2024-01, with the labels that each got.

#148 github: copy CODEOWNERS from cc-msft-prototypes
  .github/CODEOWNERS
Labels: upstream-not-needed

#147 github: add `upstream-missing` label to PR checklist
  .github/pull_request_template.md
Labels: upstream-not-needed

#151 genpolicy: don't panic without cache file
  src/tools/genpolicy/src/registry.rs
Labels: upstream-missing

#145 genpolicy: add priorityClassName as a field in PodSpec interface
  src/agent/samples/policy/yaml/pod/pod-ubuntu.yaml
  src/tools/genpolicy/src/pod.rs
Labels: upstream-missing

#156 genpolicy: add support for PodDisruptionBudget spec
  src/tools/genpolicy/src/yaml.rs
Labels: upstream-missing

#157 ci: Fix agent static checks
  .github/workflows/static-checks.yaml
  src/agent/rustjail/src/container.rs
  src/agent/src/device.rs
  src/agent/src/mount.rs
  src/agent/src/storage/mod.rs
Labels: upstream-merged
