Repository microsoft/kata-containers, pull requests merged in 2025-01, with the labels that each got.

#283 runtime: Remove unused VMM options for mem alloc
  src/runtime/config/configuration-fc.toml.in
  src/runtime/config/configuration-qemu.toml.in
Labels: upstream/not-needed

#288 samples: use 256Mi pod memory limit
  src/agent/samples/policy/yaml/webhook/webhook-pod4.yaml
  src/agent/samples/policy/yaml/webhook2/webhook-pod10.yaml
Labels: upstream/not-needed

#292 agent: add back rego error logs
  src/agent/src/policy.rs
Labels: upstream/missing

#294 agent: avoid "unknown mount flag" for tardev
  src/libs/kata-sys-util/src/mount.rs
Labels: upstream/not-needed

#296 runtime: skip empty Guest console output lines
  src/runtime/virtcontainers/sandbox.go
Labels: upstream/merged

#293 overlay: use nix::mount for OverlayFS to overcome mounting limitations
  src/overlay/Cargo.lock
  src/overlay/Cargo.toml
  src/overlay/src/main.rs
Labels: upstream/not-needed

#299 rootfs: minor systemd file deletion cleanup
  tools/osbuilder/image-builder/image_builder.sh
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: upstream/merged
