Repository microsoft/kata-containers, pull requests merged in 2025-03, with the labels that each got.

#318 node-builder: Fix SHIM_USE_DEBUG_CONFIG behavior
  tools/osbuilder/node-builder/azure-linux/README.md
  tools/osbuilder/node-builder/azure-linux/package_install.sh
Labels: upstream/not-needed

#323 config: Properly set default clh loglevel to 1
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
Labels: upstream/merged

#310 Rework kata, kata-cc images into release and debug images with different package compositions.
  tools/osbuilder/Makefile
  tools/osbuilder/igvm-builder/azure-linux/igvm_lib.sh
  tools/osbuilder/igvm-builder/igvm_builder.sh
  tools/osbuilder/node-builder/azure-linux/Makefile
  tools/osbuilder/node-builder/azure-linux/README.md
  tools/osbuilder/node-builder/azure-linux/common.sh
  tools/osbuilder/node-builder/azure-linux/package_build.sh
  tools/osbuilder/node-builder/azure-linux/package_install.sh
  tools/osbuilder/node-builder/azure-linux/uvm_build.sh
  tools/osbuilder/node-builder/azure-linux/uvm_install.sh
  tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
Labels: upstream/not-needed

#321 policy: test through agent
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/policy/Cargo.toml
  src/agent/policy/src/lib.rs
  src/agent/policy/src/policy.rs
  src/agent/src/main.rs
  src/agent/src/policy.rs
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/src/lib.rs
  src/tools/genpolicy/src/policy.rs
  src/tools/genpolicy/src/utils.rs
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/copyfile/testcases.json
Labels: upstream/merged

#334 policy: add tests for createContainerRequest
  src/agent/Cargo.lock
  src/agent/policy/Cargo.toml
  src/agent/policy/src/policy.rs
  src/agent/src/policy.rs
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/createContainer/basic/pod.yaml
  src/tools/genpolicy/tests/testdata/createContainer/basic/testcases.json
  src/tools/genpolicy/tests/testdata/createContainer/legacy/pod.yaml
  src/tools/genpolicy/tests/testdata/createContainer/legacy/testcases.json
Labels: upstream/missing
