Repository microsoft/kata-containers, pull requests merged in 2025-02, with the labels that each got.

#303 Cameronbaird/hyp loglevel
  src/runtime/config/configuration-clh-snp.toml.in
  src/runtime/config/configuration-clh.toml.in
  src/runtime/pkg/katautils/config-settings.go.in
  src/runtime/pkg/katautils/config.go
  src/runtime/pkg/katautils/config_test.go
  src/runtime/virtcontainers/clh.go
  src/runtime/virtcontainers/hypervisor.go
Labels: upstream/missing

#302 rootfs: delete more systemd files
  tools/osbuilder/rootfs-builder/rootfs.sh
Labels: upstream/not-needed

#307 node-builder: Updates to README.md
  tools/osbuilder/node-builder/azure-linux/README.md
Labels: upstream/not-needed

#313 Prepare for build with rust v1.84
  src/agent/src/config.rs
  src/libs/kata-sys-util/src/protection.rs
  src/libs/protocols/build.rs
  src/tools/genpolicy/src/registry.rs
Labels: upstream/not-needed

#309 genpolicy: add crate-scoped integration test
  .github/workflows/static-checks.yaml
  src/tools/genpolicy/Cargo.lock
  src/tools/genpolicy/Cargo.toml
  src/tools/genpolicy/Makefile
  src/tools/genpolicy/tests/main.rs
  src/tools/genpolicy/tests/testdata/copyfile/pod.yaml
  src/tools/genpolicy/tests/testdata/copyfile/testcases.json
  src/tools/genpolicy/tests/testdata/createsandbox/pod.yaml
  src/tools/genpolicy/tests/testdata/createsandbox/testcases.json
  tools/packaging/static-build/tools/Dockerfile
Labels: upstream/merged

#317 agent: Fix race condition with cgroup watchers
  .github/workflows/basic-ci-amd64.yaml
  src/agent/rustjail/src/cgroups/notifier.rs
  src/agent/src/rpc.rs
  src/runtime/virtcontainers/kata_agent.go
Labels: upstream/merged
